# Generated by Django 5.0.2 on 2024-02-15 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
